AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hands-In backend (PayPal donations + Volunteers)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128
    Architectures:
      - x86_64
    Tracing: PassThrough

Resources:
  PayPalCaptureOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-capture-paypal-order
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ../resources/lambdas/capture_paypal_order_lambda/
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          PAYPAL_BASE_URL: https://api-m.sandbox.paypal.com
      Events:
        DonationsCaptureApi:
          Type: HttpApi
          Properties:
            Path: /donations/capture
            Method: POST

  # -----------------------
  # Data Store
  # -----------------------
  VolunteersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: handsin-volunteers-dev
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # -----------------------
  # Donations (PayPal)
  # -----------------------
  PayPalCreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-create-paypal-order
      Handler: app.lambda_handler
      CodeUri: ../resources/lambdas/create_paypal_order_lambda/
      Environment:
        Variables:
          PAYPAL_BASE_URL: https://api-m.sandbox.paypal.com
      Events:
        DonationsApi:
          Type: HttpApi
          Properties:
            Path: /donations
            Method: POST

  PayPalWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-paypal-webhook
      Handler: app.lambda_handler
      CodeUri: ../resources/lambdas/paypal_webhook_lambda/
      Environment:
        Variables:
          PAYPAL_BASE_URL: https://api-m.sandbox.paypal.com
      Events:
        PayPalWebhookApi:
          Type: HttpApi
          Properties:
            Path: /paypal/webhook
            Method: POST

  # -----------------------
  # Volunteers (DynamoDB)
  # -----------------------
  CreateVolunteerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-create-volunteer
      Handler: app.lambda_handler
      CodeUri: ../resources/lambdas/create_volunteer_lambda/
      Environment:
        Variables:
          VOLUNTEER_TABLE: !Ref VolunteersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VolunteersTable
      Events:
        VolunteersCreateApi:
          Type: HttpApi
          Properties:
            Path: /volunteers
            Method: POST

  ListVolunteersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-list-volunteers
      Handler: app.lambda_handler
      CodeUri: ../resources/lambdas/list_volunteers_lambda/
      Environment:
        Variables:
          VOLUNTEER_TABLE: !Ref VolunteersTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref VolunteersTable
      Events:
        VolunteersListApi:
          Type: HttpApi
          Properties:
            Path: /volunteers
            Method: GET

  GetVolunteerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: handsin-get-volunteer
      Handler: app.lambda_handler
      CodeUri: ../resources/lambdas/get_volunteer_lambda/
      Environment:
        Variables:
          VOLUNTEER_TABLE: !Ref VolunteersTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref VolunteersTable
      Events:
        VolunteersGetApi:
          Type: HttpApi
          Properties:
            Path: /volunteers/{id}
            Method: GET

Outputs:
  HttpApiUrl:
    Description: Base URL for Hands-In HTTP API
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
